name: provenance_dart
version: 1.0.1
description: A native flutter library for interacting with the provenance wallet.
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ecdsa: 0.0.4
  grpc: 3.0.2
  protobuf: 2.1.0
  secp256k1: 0.3.0
  sha3: 0.2.0
  web_socket_channel: 2.1.0
  encrypt: ^5.0.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  mockito: ^5.0.17
