name: Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'

      - name: Restore packages
        run: flutter pub get

      - name: Run tests
        run: flutter test
